import { HouseholdData, StoreProduct, Trophy, PlaceItem, RewardItem, CustomRoutine, RoutineItemExecution } from '../types';

export const INITIAL_AFFINITY_PILLARS = [
  {
    id: 'affection',
    name: 'Affection & Cuddles',
    level: 14,
    resonance: 92,
    icon: 'favorite',
    description: 'Morning tummy rubs, lap snuggles during thunderstorms, and chin scratches recorded.',
    category: 'primary' as const,
  },
  {
    id: 'nutrition',
    name: 'Nutrition & Food',
    level: 12,
    resonance: 84,
    icon: 'restaurant',
    description: 'Consistent freeze-dried raw diet logs, pumpkin fiber boosts, and timely fresh hydration.',
    category: 'secondary' as const,
  },
  {
    id: 'play',
    name: 'Play & Agility',
    level: 15,
    resonance: 98,
    icon: 'sports_tennis',
    description: 'Daily park fetch, flirt pole sprints, and agility course hurdles. Outstanding drive!',
    category: 'tertiary' as const,
  },
  {
    id: 'outdoors',
    name: 'Outdoor Adventures',
    level: 11,
    resonance: 78,
    icon: 'hiking',
    description: 'Pine trail mountain hikes, weekend lake paddles, and sniffari exploration routes.',
    category: 'neutral' as const,
  },
  {
    id: 'grooming',
    name: 'Grooming & Spa',
    level: 9,
    resonance: 62,
    icon: 'shower',
    description: 'Oatmeal paw soaks, slicker brush detangling sessions, and lavender ear cleaning.',
    category: 'primary' as const,
  },
  {
    id: 'health',
    name: 'Healthcare & Care',
    level: 13,
    resonance: 88,
    icon: 'healing',
    description: 'Up-to-date vaccine passport, heartworm flea-tick chewables given on 1st of month.',
    category: 'tertiary' as const,
  },
  {
    id: 'rest',
    name: 'Rest & Security',
    level: 10,
    resonance: 75,
    icon: 'bedtime',
    description: 'Orthopedic memory foam naps, calming white noise routines, and cozy crate den security.',
    category: 'secondary' as const,
  },
  {
    id: 'tricks',
    name: 'Trick Training',
    level: 8,
    resonance: 55,
    icon: 'school',
    description: 'Working on reverse recall and spin cue. Clicker mastery recorded 3x this week.',
    category: 'primary' as const,
  },
];

export const INITIAL_PRODUCTS: StoreProduct[] = [
  {
    id: 'prod-1',
    title: 'Orthopedic Deep-Rest Dual Foam Den Bed',
    subtitle: 'CertiPUR-US orthopedic medical memory foam',
    category: 'Gear & Beds',
    points: 6500,
    price: 129.99,
    rating: 4.9,
    reviews: 184,
    badge: 'Veterinary Choice',
    image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=500&q=80',
    desc: 'Medical-grade dual foam cushioning designed for optimal canine spinal relief and joint recovery after long trail runs.',
    specs: ['Washable micro-velvet cover', 'Waterproof inner membrane liner', 'Anti-slip base grip'],
    inStock: true,
  },
  {
    id: 'prod-2',
    title: 'Omega-3 Wild Alaskan Salmon Oil (500ml)',
    subtitle: 'Cold-pressed sustainably caught EPA & DHA',
    category: 'Food & Nutrition',
    points: 2200,
    price: 34.50,
    rating: 4.8,
    reviews: 310,
    badge: 'Clinical Grade',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=500&q=80',
    desc: 'Cold-pressed sustainably caught Alaskan salmon oil rich in EPA and DHA to enhance skin radiance and soothe joint stiffness.',
    specs: ['Zero artificial preservatives', 'Pump bottle dispenser included', 'Veterinary formulation'],
    inStock: true,
  },
  {
    id: 'prod-3',
    title: 'Aerodynamic Natural Rubber Fetch Disc',
    subtitle: 'Gentle dental-safe aerodynamic flight',
    category: 'Toys & Agility',
    points: 1200,
    price: 19.00,
    rating: 4.7,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?auto=format&fit=crop&w=500&q=80',
    desc: 'Soft pliable natural rubber that is gentle on teeth and gums while providing high-flying stability in coastal winds.',
    specs: ['Puncture-resistant rubber', 'Floats in water', 'High-visibility safety orange'],
    inStock: true,
  },
  {
    id: 'prod-4',
    title: 'Advanced Hip & Joint Glucosamine Chews (120ct)',
    subtitle: 'NASC Certified Cartilage & Synovial Fluid Formula',
    category: 'Wellness & Care',
    points: 2800,
    price: 46.95,
    rating: 5.0,
    reviews: 245,
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=500&q=80',
    desc: 'Clinically formulated soft chews containing Glucosamine HCl, Chondroitin, MSM, and Organic Turmeric for cartilage health.',
    specs: ['Tasty duck & liver flavor', 'Certified NASC seal', 'Veterinary recommended'],
    inStock: true,
  },
  {
    id: 'prod-5',
    title: 'Stainless Steel Silent Waterfall Fountain (3.2L)',
    subtitle: 'Hygienic 304 stainless steel circulating filter',
    category: 'Wellness & Care',
    points: 3900,
    price: 64.00,
    rating: 4.9,
    reviews: 184,
    badge: 'Vet Recommended',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=500&q=80',
    desc: 'Hygienic 304 stainless steel automated water circulation fountain with multi-stage coconut carbon filtration.',
    specs: ['Whisper-quiet pump (<20dB)', 'Dishwasher safe body', 'Includes 3 replacement filters'],
    inStock: true,
  },
  {
    id: 'prod-6',
    title: 'Freeze-Dried Raw Pacific Salmon & Venison Bites (16oz)',
    subtitle: '100% human-grade single-protein topper',
    category: 'Food & Nutrition',
    points: 2400,
    price: 36.00,
    rating: 4.9,
    reviews: 420,
    badge: 'Raw Diet',
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=500&q=80',
    desc: 'Single-ingredient freeze-dried wild salmon treats crafted for high-value trick training and meal topper boosts.',
    specs: ['100% Wild Salmon & Venison', 'High protein (64%)', 'Grain and gluten-free'],
    inStock: true,
  },
  {
    id: 'prod-7',
    title: 'Active Cellular Smart GPS Dog Collar',
    subtitle: 'Real-time 24/7 radar tracking & escape alerts',
    category: 'Gear & Beds',
    points: 9500,
    price: 189.00,
    rating: 4.8,
    reviews: 112,
    badge: 'Smart Tech',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=500&q=80',
    desc: 'Sub-meter cellular GPS positioning collar with live escape boundary notifications and sleep restlessness tracking.',
    specs: ['Waterproof IP68 rating', 'Up to 3 months battery life', 'Works nationwide on LTE-M'],
    inStock: true,
  },
  {
    id: 'prod-8',
    title: 'Hands-Free Shock-Absorbing Bungee Trail Leash',
    subtitle: 'Aviation aluminum clip & dual traffic control handles',
    category: 'Gear & Beds',
    points: 2600,
    price: 42.00,
    rating: 4.8,
    reviews: 167,
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=500&q=80',
    desc: 'Reflective waist-worn running leash with dual shock absorbers to protect both owner and dog during trail sprints.',
    specs: ['Adjustable waist belt (28-48 in)', 'Dual control traffic handles', 'Aviation aluminum clip'],
    inStock: true,
  },
  {
    id: 'prod-9',
    title: 'Clinical Dental Plaque Enzymatic Toothpaste & Finger Brush',
    subtitle: 'Enzymatic TartarControl formula with chlorhexidine',
    category: 'Wellness & Care',
    points: 1600,
    price: 24.00,
    rating: 4.7,
    reviews: 135,
    badge: 'Oral Care',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=500&q=80',
    desc: 'Veterinary dental paste that breaks down subgingival biofilms and neutralizes bad breath without foaming or rinsing.',
    specs: ['Poultry flavored', 'Fluoride-free', 'Includes soft silicone dual-head brush'],
    inStock: true,
  },
  {
    id: 'prod-10',
    title: 'Interactive Level 3 Complex Brain Wooden Puzzle Feeder',
    subtitle: 'Mental enrichment sliding tile & drawer labyrinth',
    category: 'Toys & Agility',
    points: 2300,
    price: 38.00,
    rating: 4.6,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=500&q=80',
    desc: 'Mental stimulation puzzle that slows down fast eaters and exercises canine problem-solving instincts.',
    specs: ['BPA, PVC & Phthalate Free', 'Non-slip rubber base', 'Easy warm water cleaning'],
    inStock: true,
  },
  {
    id: 'prod-11',
    title: 'Probiotic Digestive Enzymes & Pumpkin Fiber Powder (250g)',
    subtitle: '5 Billion CFU viable microflora for gut microbiome stability',
    category: 'Food & Nutrition',
    points: 2100,
    price: 32.00,
    rating: 4.9,
    reviews: 198,
    badge: 'Microbiome',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=500&q=80',
    desc: 'Prebiotic and probiotic meal topper restoring stool consistency and easing digestive sensitivity in active pets.',
    specs: ['Organic Ceylon pumpkin', '6 probiotic strains', 'Scoop included'],
    inStock: true,
  },
  {
    id: 'prod-12',
    title: 'Soothing Oatmeal & Lavender Medicated Paw Balm (4oz)',
    subtitle: 'Organic beeswax and shea butter hyperkeratosis barrier',
    category: 'Wellness & Care',
    points: 1400,
    price: 18.50,
    rating: 4.8,
    reviews: 154,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=500&q=80',
    desc: 'Lick-safe intensive organic balm protecting paw pads and noses from rough asphalt, trail grit, and cold weather.',
    specs: ['100% Organic certified ingredients', 'Zero synthetic fragrances', 'Deep moisturizing shield'],
    inStock: true,
  },
  {
    id: 'prod-13',
    title: 'Microchip Automatic Selective RFID Feeder with Sealed Lid',
    subtitle: 'Prevents food stealing with integrated RFID collar scanner',
    category: 'Wellness & Care',
    points: 8800,
    price: 159.00,
    rating: 4.9,
    reviews: 86,
    badge: 'Exclusive',
    image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=500&q=80',
    desc: 'Motorized smart feeder that unlocks only for your designated pet’s RFID collar tag, keeping prescription food secure.',
    specs: ['Sealed rubber aroma ring', 'Split bowl inserts included', 'Compatible with all microchips'],
    inStock: true,
  },
  {
    id: 'prod-14',
    title: 'Therapeutic Calming Pheromone Diffuser & Refill Kit',
    subtitle: 'Clinically proven maternal appeasing pheromone replica',
    category: 'Wellness & Care',
    points: 2500,
    price: 39.95,
    rating: 4.7,
    reviews: 172,
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=500&q=80',
    desc: 'Continuous vapor diffuser emitting natural calming pheromones to ease thunderstorm anxiety and separation distress.',
    specs: ['Covers up to 700 sq ft', 'Drug-free relaxation', '30-day continuous refill'],
    inStock: true,
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'rew-dental',
    title: 'Ultrasonic Dental Prophylaxis & Polish Under Anesthesia',
    description: 'Comprehensive oral exam, full-mouth intraoral digital X-rays, ultrasonic subgingival calculus scaling, and enamel polish.',
    pointsCost: 16500,
    retailValue: '$380.00 Clinical Value',
    requiredLevel: 8,
    requiredLevelTitle: 'Best Buddies (Lvl 8+)',
    category: 'clinical',
    icon: '🦷',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=600&q=80',
    terms: 'Valid at accredited Bay Paws Veterinary surgical suites. Includes pre-anesthetic blood screening and IV fluid support.',
    partnerClinic: 'Bay Paws Veterinary Specialty & Dental Clinic',
  },
  {
    id: 'rew-emergency',
    title: 'Emergency Trauma & ICU Credit Voucher ($500 Value)',
    description: 'Dedicated financial safety buffer covering emergency room diagnostics, oxygen therapy, CT imaging, and surgical intervention.',
    pointsCost: 25000,
    retailValue: '$500.00 Direct Credit',
    requiredLevel: 12,
    requiredLevelTitle: 'Master Guardian (Lvl 12+)',
    category: 'clinical',
    icon: '🏥',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80',
    terms: 'Honored 24/7 at all certified Level 1 emergency trauma pet hospitals. Balance carries forward if unused. Never expires.',
    partnerClinic: 'Bay Paws 24/7 Trauma ICU & Emergency Center',
  },
  {
    id: 'rew-gps',
    title: 'Smart Cellular GPS Radar Collar & 1-Year Satellite Plan',
    description: 'Hardware tracking collar with live satellite map pinpoints, escape geofence perimeter alerts, and 24/7 biometric activity monitoring.',
    pointsCost: 11500,
    retailValue: '$240.00 Hardware Value',
    requiredLevel: 6,
    requiredLevelTitle: 'Devoted Pal (Lvl 6+)',
    category: 'gear',
    icon: '🛰️',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=600&q=80',
    terms: 'Delivered directly to household with 12 months prepaid cellular LTE telemetry subscription included.',
    partnerClinic: 'Fi Smart Collar Technologies / PAWdiCURE Hardware',
  },
  {
    id: 'rew-behaviorist',
    title: 'Board-Certified Veterinary Behaviorist 1-on-1 Consultation',
    description: 'Comprehensive 90-minute clinical behavioral consultation diagnosing separation anxiety, sound sensitivity, or leash reactivity.',
    pointsCost: 10200,
    retailValue: '$225.00 Clinical Value',
    requiredLevel: 7,
    requiredLevelTitle: 'Inseparable (Lvl 7+)',
    category: 'therapeutic',
    icon: '🧠',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    terms: 'Telehealth video or in-clinic consultation with written behavioral modification protocol and follow-up support.',
    partnerClinic: 'Bay Area Veterinary Behavioral Institute',
  },
  {
    id: 'rew-wellness-exam',
    title: 'Annual Comprehensive Wellness Exam & 27-Panel CBC Bloodwork',
    description: 'Head-to-tail clinical physical assessment, complete blood count, kidney and hepatic biochemistry panel, and lifestyle consultation.',
    pointsCost: 8900,
    retailValue: '$195.00 Clinical Value',
    requiredLevel: 4,
    requiredLevelTitle: 'Loyal Friend (Lvl 4+)',
    category: 'diagnostic',
    icon: '🩺',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80',
    terms: 'Requires appointment scheduling 7 days in advance. Digital pathology lab report delivered within 48 hours.',
    partnerClinic: 'Pacific Heights Veterinary Medical Center',
  },
  {
    id: 'rew-dna-screen',
    title: 'Whole-Genome Breed & 350+ Genetic Risk Screening Kit',
    description: 'At-home DNA swab analyzing 350+ hereditary disease markers, drug sensitivity (MDR1), cardiac risks, and ancestral lineage.',
    pointsCost: 7200,
    retailValue: '$169.00 Diagnostic Value',
    requiredLevel: 3,
    requiredLevelTitle: 'Trusted Companion (Lvl 3+)',
    category: 'diagnostic',
    icon: '🧬',
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=600&q=80',
    terms: 'Prepaid lab return packaging included. Certified genetic test report synced to PAWdiCURE Medical Chart.',
    partnerClinic: 'Embark Precision Genetics Laboratory',
  },
  {
    id: 'rew-parasite-pack',
    title: '6-Month Complete Parasite & Heartworm Prevention Supply',
    description: '6-month box of veterinary prescription oral Simparica Trio or Credelio Plus chewables preventing heartworm, ticks, and fleas.',
    pointsCost: 6800,
    retailValue: '$145.00 Pharmacy Value',
    requiredLevel: 3,
    requiredLevelTitle: 'Trusted Companion (Lvl 3+)',
    category: 'clinical',
    icon: '💊',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=600&q=80',
    terms: 'Requires valid prescription authorization on file with your designated clinic.',
    partnerClinic: 'Bay Paws Clinical Veterinary Pharmacy',
  },
  {
    id: 'rew-hydrotherapy',
    title: 'Underwater Treadmill Hydrotherapy & Physical Rehab Session',
    description: '45-minute therapeutic aquatic treadmill session supervised by a licensed canine rehabilitation practitioner (CCRP).',
    pointsCost: 6400,
    retailValue: '$135.00 Therapy Value',
    requiredLevel: 5,
    requiredLevelTitle: 'True Partner (Lvl 5+)',
    category: 'therapeutic',
    icon: '🌊',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80',
    terms: 'Includes biometric gait velocity assessment and heated thermal post-swim blow dry.',
    partnerClinic: 'Bay Area Canine Aquatic Therapy Center',
  },
  {
    id: 'rew-ozone-spa',
    title: 'Artisan Ozone Microbubble Fur Spa & Medicated Deshedding',
    description: 'Deep pore ozone water immersion eliminating allergens, followed by botanical argan coat treatment, blueberry facial, and paw massage.',
    pointsCost: 5400,
    retailValue: '$110.00 Spa Value',
    requiredLevel: 3,
    requiredLevelTitle: 'Trusted Companion (Lvl 3+)',
    category: 'wellness',
    icon: '🛁',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80',
    terms: 'Appointment required. Available Tuesday through Saturday at the artisan grooming pavilion.',
    partnerClinic: 'Artisan Grooming Spa & Botanical Sanctuary',
  },
  {
    id: 'rew-raw-box',
    title: '1-Month Organic Freeze-Dried Raw Superfood Feast Box',
    description: 'Curated 30-day nutrition box with wild Alaskan salmon, grass-fed venison, organic kelp minerals, and cold-pressed pumpkin fiber.',
    pointsCost: 4500,
    retailValue: '$98.00 Nutrition Value',
    requiredLevel: 2,
    requiredLevelTitle: 'Friendly Buddy (Lvl 2+)',
    category: 'wellness',
    icon: '🥩',
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=600&q=80',
    terms: 'Ships in temperature-controlled biodegradable insulated packaging directly to your doorstep.',
    partnerClinic: 'Primal Organic Pet Nutrition Labs',
  },
];

export const INITIAL_PLACES: PlaceItem[] = [
  {
    id: 'place-1',
    name: 'Presidio Mountain Pines & Off-Leash Trail',
    category: 'park',
    address: 'Presidio Trailhead 4, San Francisco, CA',
    distance: '1.2 miles away',
    rating: 4.9,
    reviews: 320,
    phone: '+1 (415) 561-4323',
    openNow: true,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80',
    isFavorite: true,
    features: ['Off-Leash Permitted', 'Water Stations', 'Shaded Trails', 'Waste Bins'],
  },
  {
    id: 'place-2',
    name: 'Bay Paws Veterinary Specialty & Emergency Center',
    category: 'vet',
    address: '1420 Marina Blvd, San Francisco, CA',
    distance: '0.8 miles away',
    rating: 4.9,
    reviews: 215,
    phone: '+1 (555) 019-2834',
    openNow: true,
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=500&q=80',
    isFavorite: true,
    features: ['24/7 Trauma ICU', 'Digital Radiology', 'Surgery Suite', 'Pharmacy On-Site'],
  },
  {
    id: 'place-3',
    name: 'The Wag Bar & Botanical Dog Cafe',
    category: 'cafe',
    address: '782 Chestnut St, San Francisco, CA',
    distance: '1.8 miles away',
    rating: 4.8,
    reviews: 145,
    phone: '+1 (415) 890-1122',
    openNow: true,
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=500&q=80',
    isFavorite: false,
    features: ['Puppuccino Menu', 'Outdoor Heated Patio', 'Artisan Pastries', 'Dog Social Hours'],
  },
  {
    id: 'place-4',
    name: 'Artisan Grooming Spa & Hydrotherapy Tub',
    category: 'groomer',
    address: '320 Bayview Ave, San Francisco, CA',
    distance: '2.4 miles away',
    rating: 4.9,
    reviews: 88,
    phone: '+1 (415) 771-4400',
    openNow: false,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=500&q=80',
    isFavorite: false,
    features: ['Oatmeal Paw Soaks', 'Deshedding Air-Dry', 'Gentle Dental Polish', 'Calming Aromatherapy'],
  },
  {
    id: 'place-5',
    name: 'Crissy Field Coastal Beach Run',
    category: 'park',
    address: '1199 E Beach, San Francisco, CA',
    distance: '2.9 miles away',
    rating: 5.0,
    reviews: 580,
    phone: '+1 (415) 561-4323',
    openNow: true,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80',
    isFavorite: true,
    features: ['Sandy Beach', 'Golden Gate Views', 'Tidal Pool Sniffing', 'Shower Rinses'],
  },
];

export const INITIAL_TROPHIES: Trophy[] = [
  {
    id: 'tr-1',
    title: 'First Nourishment',
    subtitle: 'Administered calibrated meal with toppers',
    icon: 'restaurant',
    color: '#ff6b4a',
    unlocked: true,
    category: 'Nutrition',
  },
  {
    id: 'tr-2',
    title: '7-Day Care Streak',
    subtitle: 'Kept daily routines unbroken for 7 consecutive days',
    icon: 'local_fire_department',
    color: '#f59e0b',
    unlocked: true,
    category: 'Consistency',
  },
  {
    id: 'tr-3',
    title: 'Memory Keeper',
    subtitle: 'Recorded 5 milestone memories with high-res photos',
    icon: 'photo_camera',
    color: '#3b82f6',
    unlocked: true,
    category: 'Bonding',
  },
  {
    id: 'tr-4',
    title: 'Clinical Sentinel',
    subtitle: 'Logged immunization record and preventative dosing',
    icon: 'health_and_safety',
    color: '#10b981',
    unlocked: true,
    category: 'Health',
  },
  {
    id: 'tr-5',
    title: 'Trail Blazer',
    subtitle: 'Completed 5 vigorous outdoor adventure walks',
    icon: 'hiking',
    color: '#8b5cf6',
    unlocked: true,
    category: 'Agility',
  },
  {
    id: 'tr-6',
    title: 'Master Communicator',
    subtitle: 'Consulted PAWdiCURE AI for personalized breed guidance',
    icon: 'psychology',
    color: '#ec4899',
    unlocked: false,
    category: 'Intelligence',
  },
];

export const INITIAL_HOUSEHOLD_DATA: HouseholdData = {
  householdId: 'default-household',
  syncCode: 'MILO-88',
  activePetId: 'milo',
  streakDays: 12,
  pawPoints: 4820,
  wishlist: ['prod-1', 'prod-5'],
  cart: [
    { productId: 'prod-2', quantity: 1 },
  ],
  lastSyncedAt: Date.now(),
  userProfile: {
    name: 'Sarah Miller',
    email: 'sarah.miller@pawdicure.app',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    theme: 'light',
    notifications: {
      feeding: true,
      medications: true,
      walks: true,
      health: true,
      achievements: true,
    },
    privacy: {
      locationSharing: true,
      cloudSync: true,
      publicProfile: false,
    },
  },
  familyMembers: [
    {
      id: 'fam-1',
      name: 'Sarah Miller',
      email: 'sarah@pawdicure.app',
      role: 'Owner',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      isPrimary: true,
    },
    {
      id: 'fam-2',
      name: 'Arun Patel',
      email: 'arun@patel.me',
      role: 'Family Member',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    },
    {
      id: 'fam-3',
      name: 'Dr. Elena Rostova',
      email: 'elena@baypawsvet.com',
      role: 'Caregiver',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=150&q=80',
    },
  ],
  careActivities: [
    {
      id: 'act-1',
      petId: 'milo',
      actorName: 'Sarah',
      action: 'Administered 180g supper with Salmon Oil topper',
      time: '12m ago',
      timestamp: Date.now() - 12 * 60 * 1000,
      xp: 25,
      icon: 'restaurant',
    },
    {
      id: 'act-2',
      petId: 'milo',
      actorName: 'Arun',
      action: 'Completed 35m vigorous coastal sniffari walk',
      time: '2h ago',
      timestamp: Date.now() - 2 * 3600 * 1000,
      xp: 35,
      icon: 'hiking',
    },
    {
      id: 'act-3',
      petId: 'milo',
      actorName: 'Sarah',
      action: 'Dispensed daily Glucosamine Joint chew',
      time: '5h ago',
      timestamp: Date.now() - 5 * 3600 * 1000,
      xp: 20,
      icon: 'medication',
    },
    {
      id: 'act-4',
      petId: 'milo',
      actorName: 'Dr. Elena',
      action: 'Updated DHPP 5-in-1 antibody booster schedule',
      time: 'Yesterday',
      timestamp: Date.now() - 24 * 3600 * 1000,
      xp: 40,
      icon: 'healing',
    },
  ],
  activities: [
    {
      id: 'act-init-1',
      petId: 'milo',
      activityType: 'feeding',
      title: 'Nutritious Breakfast Portion',
      durationMinutes: 5,
      intensity: 'light',
      date: new Date().toISOString().slice(0, 10),
      startTime: '8:10 AM',
      amountGrams: 180,
      notes: 'Salmon Oil topper added. Eager appetite!',
      source: 'manual',
      xpEarned: 20,
      icon: '🍖',
      createdAt: Date.now() - 4 * 3600 * 1000,
      updatedAt: Date.now() - 4 * 3600 * 1000,
    },
    {
      id: 'act-init-2',
      petId: 'milo',
      activityType: 'walk',
      title: 'Morning Park Sniffari',
      durationMinutes: 25,
      intensity: 'moderate',
      date: new Date().toISOString().slice(0, 10),
      startTime: '10:30 AM',
      location: 'Riverside Greenway',
      calories: 110,
      distanceKm: 1.8,
      notes: 'Gentle pace with lots of sniffing and social greeting.',
      source: 'manual',
      xpEarned: 30,
      icon: '🐾',
      createdAt: Date.now() - 2 * 3600 * 1000,
      updatedAt: Date.now() - 2 * 3600 * 1000,
    },
    {
      id: 'act-init-3',
      petId: 'milo',
      activityType: 'play',
      title: 'Tug & Fetch Playtime',
      durationMinutes: 15,
      intensity: 'high',
      date: new Date().toISOString().slice(0, 10),
      startTime: '3:45 PM',
      calories: 85,
      notes: 'High energy session with favorite rope toy!',
      source: 'manual',
      xpEarned: 25,
      icon: '🎾',
      createdAt: Date.now() - 45 * 60 * 1000,
      updatedAt: Date.now() - 45 * 60 * 1000,
    }
  ],
  places: INITIAL_PLACES,
  trophies: INITIAL_TROPHIES,
  products: INITIAL_PRODUCTS,
  rewards: INITIAL_REWARDS,
  redeemedRewards: [
    {
      id: 'red-1',
      rewardId: 'rew-free-dental',
      title: 'Artisan Dental Polish & Brush Session',
      pointsSpent: 1200,
      redeemedAt: 'Sep 10, 2026',
      code: 'PAW-DENT-8821',
    },
  ],
  weightHistory: [
    { id: 'w-1', petId: 'milo', date: 'May 1', weightKg: 27.2 },
    { id: 'w-2', petId: 'milo', date: 'Jun 15', weightKg: 27.8 },
    { id: 'w-3', petId: 'milo', date: 'Jul 20', weightKg: 28.1 },
    { id: 'w-4', petId: 'milo', date: 'Aug 10', weightKg: 28.3 },
    { id: 'w-5', petId: 'milo', date: 'Sep 14', weightKg: 28.4 },
    { id: 'w-6', petId: 'luna', date: 'Jun 1', weightKg: 4.5 },
    { id: 'w-7', petId: 'luna', date: 'Jul 1', weightKg: 4.7 },
    { id: 'w-8', petId: 'luna', date: 'Aug 1', weightKg: 4.8 },
  ],
  feedingHistory: [
    {
      id: 'feed-1',
      petId: 'milo',
      time: '08:15 AM',
      date: 'Today',
      grams: 180,
      calories: 620,
      foodType: 'Pacific Salmon & Sweet Potato',
      toppers: ['Salmon Oil (2 pumps)'],
    },
    {
      id: 'feed-2',
      petId: 'milo',
      time: '06:30 PM',
      date: 'Yesterday',
      grams: 180,
      calories: 645,
      foodType: 'Pacific Salmon & Sweet Potato',
      toppers: ['Salmon Oil (2 pumps)', 'Glucosamine Chew'],
    },
    {
      id: 'feed-3',
      petId: 'milo',
      time: '08:00 AM',
      date: 'Yesterday',
      grams: 180,
      calories: 620,
      foodType: 'Pacific Salmon & Sweet Potato',
      toppers: ['Salmon Oil (2 pumps)'],
    },
    {
      id: 'feed-luna-1',
      petId: 'luna',
      time: '12:00 PM',
      date: 'Today',
      grams: 65,
      calories: 220,
      foodType: 'Freeze-Dried Raw Rabbit & Salmon Pate',
      toppers: ['Probiotic Pumpkin Powder'],
    },
    {
      id: 'feed-luna-2',
      petId: 'luna',
      time: '07:30 AM',
      date: 'Today',
      grams: 65,
      calories: 225,
      foodType: 'Freeze-Dried Raw Rabbit & Salmon Pate',
      toppers: ['Salmon Oil (1 pump)'],
    },
  ],
  reminders: [
    {
      id: 'rem-1',
      petId: 'milo',
      type: 'feeding',
      title: 'Evening Salmon Supper & Omega Boost',
      date: '2026-09-15',
      time: '18:30',
      repeat: 'Daily',
      priority: 'high',
      completed: false,
      enabled: true,
      notes: '180g portion with 2 pumps wild salmon oil',
    },
    {
      id: 'rem-2',
      petId: 'milo',
      type: 'medication',
      title: 'Glucosamine Joint Cartilage Chew',
      date: '2026-09-15',
      time: '09:00',
      repeat: 'Daily',
      priority: 'medium',
      completed: true,
      enabled: true,
      notes: 'Give with or right after breakfast',
    },
    {
      id: 'rem-3',
      petId: 'milo',
      type: 'walk',
      title: 'Crissy Field Sunset Beach Sprint',
      date: '2026-09-15',
      time: '17:45',
      repeat: 'Daily',
      priority: 'medium',
      completed: false,
      enabled: true,
      notes: 'Pack rubber fetch disc and hydration bottle',
    },
    {
      id: 'rem-4',
      petId: 'milo',
      type: 'vaccination',
      title: 'DHPP 5-in-1 Booster Appointment',
      date: '2026-10-18',
      time: '10:30',
      repeat: 'None',
      priority: 'high',
      completed: false,
      enabled: true,
      notes: 'Bay Paws Veterinary Clinic with Dr. Rostova',
    },
    {
      id: 'rem-5',
      petId: 'milo',
      type: 'grooming',
      title: 'Lavender Paw Soak & Detangle Brush',
      date: '2026-09-18',
      time: '16:00',
      repeat: 'Weekly',
      priority: 'low',
      completed: false,
      enabled: true,
      notes: 'Clean ears with veterinary cleanser',
    },
    {
      id: 'rem-luna-1',
      petId: 'luna',
      type: 'feeding',
      title: 'Evening Rabbit Pate Supper (65g)',
      date: '2026-09-15',
      time: '18:00',
      repeat: 'Daily',
      priority: 'high',
      completed: false,
      enabled: true,
      notes: '65g raw pate with 1 pump salmon oil',
    },
    {
      id: 'rem-luna-2',
      petId: 'luna',
      type: 'medication',
      title: 'Revolution Plus Monthly Topical Dose',
      date: '2026-10-01',
      time: '08:30',
      repeat: 'Monthly',
      priority: 'high',
      completed: false,
      enabled: true,
      notes: 'Apply to base of neck between shoulder blades',
    },
    {
      id: 'rem-luna-3',
      petId: 'luna',
      type: 'grooming',
      title: 'Velvet Undercoat Slicker Detangling',
      date: '2026-09-16',
      time: '19:30',
      repeat: 'Weekly',
      priority: 'medium',
      completed: false,
      enabled: true,
      notes: 'Gentle brush around ruff and tail',
    },
    {
      id: 'rem-luna-4',
      petId: 'luna',
      type: 'vaccination',
      title: 'FVRCP Feline Core Annual Booster',
      date: '2026-11-12',
      time: '14:00',
      repeat: 'None',
      priority: 'medium',
      completed: false,
      enabled: true,
      notes: 'Feline Care Center with Dr. Mark Wu',
    },
  ],
  vetVisits: [
    {
      id: 'visit-1',
      petId: 'milo',
      vetName: 'Dr. Elena Rostova',
      clinic: 'Bay Paws Veterinary Specialty Center',
      date: '2026-06-12',
      reason: 'Annual Wellness Examination & Senior Blood Panel',
      diagnosis: 'Robust musculoskeletal condition; clear cardiac rhythm.',
      treatment: 'Recommended maintaining daily Omega-3 lipid supplementation.',
      notes: 'Weight optimal at 28.4 kg. Dental prophylaxis scheduled for early 2027.',
      cost: '$185.00',
      documents: ['Clinical_Summary_June2026.pdf'],
    },
    {
      id: 'visit-2',
      petId: 'milo',
      vetName: 'Dr. Mark Wu',
      clinic: 'Marina Urgent Care Pet Hospital',
      date: '2026-02-04',
      reason: 'Right Forepaw Thorn Extraction',
      diagnosis: 'Superficial interdigital thorn puncture without infection.',
      treatment: 'Sterile removal, chlorhexidine flush, topical silver sulfadiazine.',
      notes: 'Bandage removed after 48h. Healed completely within 4 days.',
      cost: '$92.00',
      documents: ['Urgent_Care_Discharge_Feb2026.pdf'],
    },
    {
      id: 'visit-luna-1',
      petId: 'luna',
      vetName: 'Dr. Mark Wu',
      clinic: 'Feline Care Center of San Francisco',
      date: '2026-05-18',
      reason: 'Annual Feline Comprehensive Health Exam',
      diagnosis: 'Clear breath sounds, healthy dental status, coat radiant.',
      treatment: 'Administered PureVax Rabies booster and prescribed Revolution Plus.',
      notes: 'Weight steady at 4.8 kg. No sign of feline gingivostomatitis.',
      cost: '$140.00',
      documents: ['Luna_Feline_Wellness_Cert.pdf'],
    },
  ],
  pets: {
    milo: {
      id: 'milo',
      name: 'Milo',
      species: 'Dog',
      breed: 'Golden Retriever',
      age: '2y 4m',
      gender: 'Male',
      personality: ['Adventurous', 'Cuddle Bug', 'Ball-Obsessed', 'Gentle'],
      weight: 28.4,
      restingBpm: 74,
      mood: 'Playful & Ready to Explore! 🎾',
      healthStatus: 'Optimal (Up-to-Date)',
      careScore: 87,
      level: 12,
      levelTitle: 'Best Buddies',
      xp: 2450,
      nextLevelXp: 3000,
      hungerPercent: 45,
      targetPortionGrams: 180,
      dailyGramsFed: 180,
      dailyGramsGoal: 360,
      dailyCaloriesFed: 620,
      dailyCaloriesGoal: 1240,
      nutritionPercent: 50,
      lastFed: '5h ago',
      mealsToday: 2,
      maxMeals: 3,
      hydrationPercent: 77,
      hydrationMl: 580,
      goalMl: 750,
      pantryKg: 5.2,
      avatarUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=500&q=80',
      vetClinic: 'Bay Paws Clinic • Dr. Elena Rostova',
      microchipId: '985141002938472',
      bloodType: 'DEA 1.1 Negative',
      allergies: ['Chicken byproduct', 'Penicillin'],
      medicalConditions: ['Mild Grass Pollen Sensitivity'],
      emergencyContact: 'Sarah Miller (Owner)',
      emergencyPhone: '+1 (555) 019-2834',
      affinityPillars: INITIAL_AFFINITY_PILLARS,
      stepsToday: 8250,
      stepsGoal: 10000,
      caloriesBurned: 420,
      currentMl: 580,
      sleepHours: 9.2,
    },
    luna: {
      id: 'luna',
      name: 'Luna',
      species: 'Cat',
      breed: 'Ragdoll',
      age: '1y 8m',
      gender: 'Female',
      personality: ['Quiet Observer', 'Lap Purrer', 'Sunbeam Chaser'],
      weight: 4.8,
      restingBpm: 120,
      mood: 'Purring & Lounging 💤',
      healthStatus: 'Good (Dental Check Soon)',
      careScore: 92,
      level: 8,
      levelTitle: 'Cozy Companion',
      xp: 1420,
      nextLevelXp: 2000,
      hungerPercent: 20,
      targetPortionGrams: 65,
      dailyGramsFed: 130,
      dailyGramsGoal: 195,
      dailyCaloriesFed: 445,
      dailyCaloriesGoal: 670,
      nutritionPercent: 67,
      lastFed: '2h ago',
      mealsToday: 3,
      maxMeals: 4,
      hydrationPercent: 85,
      hydrationMl: 210,
      goalMl: 250,
      pantryKg: 3.1,
      avatarUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=500&q=80',
      vetClinic: 'Feline Care Center • Dr. Mark Wu',
      microchipId: '847291048201948',
      bloodType: 'Type A',
      allergies: ['Grain Fillers'],
      medicalConditions: ['None recorded'],
      emergencyContact: 'Sarah Miller (Owner)',
      emergencyPhone: '+1 (555) 019-2834',
      affinityPillars: INITIAL_AFFINITY_PILLARS.map((p) => ({ ...p, resonance: Math.max(50, p.resonance - 8) })),
      stepsToday: 3200,
      stepsGoal: 5000,
      caloriesBurned: 145,
      currentMl: 210,
      sleepHours: 13.5,
    },
  },
  memories: [
    {
      id: 'mem-1',
      petId: 'milo',
      title: 'Pine Needle Trail Summit Peak',
      date: 'May 14, 2026',
      xp: 120,
      location: 'Mt. Tamalpais Ridge',
      desc: 'First mountain summit hike! Milo proudly navigated the rocky switchbacks and earned a dip in the alpine spring.',
      tags: ['Trail Run', 'Summit', 'Adventure', 'Spring 2026'],
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80',
      createdAt: Date.now() - 3600000 * 24 * 60,
    },
    {
      id: 'mem-2',
      petId: 'milo',
      title: 'Golden Sunset Surf & Frisbee Fetch',
      date: 'Jun 28, 2026',
      xp: 150,
      location: 'Ocean Beach Pier',
      desc: 'High tides and joyful leaps catching the rubber disc in mid-air right as the golden hour sun dipped below the fog line.',
      tags: ['Beach', 'Golden Hour', 'Agility', 'Summer'],
      imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=500&q=80',
      createdAt: Date.now() - 3600000 * 24 * 30,
    },
    {
      id: 'mem-3',
      petId: 'milo',
      title: '2nd Birthday Peanut Butter Bark-Cake',
      date: 'Aug 04, 2026',
      xp: 200,
      location: 'Home Backyard Lawn',
      desc: 'Celebrated the big 2! Baked an organic pumpkin and peanut butter cake. Milo sat politely until the birthday song ended.',
      tags: ['Milestone', 'Birthday', 'Feast', 'Family'],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=500&q=80',
      createdAt: Date.now() - 3600000 * 24 * 12,
    },
    {
      id: 'mem-luna-1',
      petId: 'luna',
      title: 'Sunbeam Hammock Snooze & Gentle Purrs',
      date: 'Jul 19, 2026',
      xp: 130,
      location: 'Living Room Bay Window',
      desc: 'Luna claimed the elevated velvet windowsill perch, basking in 3 continuous hours of warm afternoon sunbeam warmth.',
      tags: ['Sunbeam', 'Feline Peace', 'Nap', 'Cozy'],
      imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=500&q=80',
      createdAt: Date.now() - 3600000 * 24 * 45,
    },
    {
      id: 'mem-luna-2',
      petId: 'luna',
      title: 'Balcony Birdsong Sniff & Feather Chase',
      date: 'Aug 22, 2026',
      xp: 140,
      location: 'Garden Greenhouse',
      desc: 'Chirping at hummingbirds and executing acrobatic vertical leaps chasing the peacock wand feather toy.',
      tags: ['Hunting Drive', 'Feather Wand', 'Play', 'Summer'],
      imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=500&q=80',
      createdAt: Date.now() - 3600000 * 24 * 20,
    },
  ],
  vaccinationHistory: [
    {
      id: 'vac-1',
      petId: 'milo',
      name: 'DHPP 5-in-1 (Distemper, Parvo, Adenovirus)',
      category: 'Core',
      status: 'Due',
      alert: true,
      dueDate: 'Oct 18, 2026',
      administeredDate: 'Oct 14, 2025',
      vet: 'Bay Paws Clinic • Dr. Elena Rostova',
      tagNumber: 'DHPP-882194',
      notes: 'Subcutaneous injection; no adverse allergic reaction noted.',
      completed: false,
      isPrediction: false,
      manufacturer: 'Zoetis Vanguard',
      batchNumber: 'ZV-18293-B2',
      verificationLevel: 'Clinic Verified',
    },
    {
      id: 'vac-2',
      petId: 'milo',
      name: 'Rabies 3-Year Core Vaccine',
      category: 'Core',
      status: 'Administered',
      alert: false,
      dueDate: 'Aug 14, 2028',
      administeredDate: 'Aug 14, 2025',
      vet: 'Bay Paws Clinic • Dr. Elena Rostova',
      tagNumber: 'RAB-992018-CA',
      notes: 'Official county registration tag #48201.',
      completed: true,
      isPrediction: false,
      manufacturer: 'Merck Nobivac',
      batchNumber: 'MN-99201-R3',
      verificationLevel: 'Laboratory Confirmed',
    },
    {
      id: 'vac-3',
      petId: 'milo',
      name: 'Bordetella Bronchiseptica (Kennel Cough)',
      category: 'Lifestyle',
      status: 'Administered',
      alert: false,
      dueDate: 'Nov 02, 2026',
      administeredDate: 'Nov 02, 2025',
      vet: 'Bay Paws Clinic • Dr. Elena Rostova',
      tagNumber: 'BOR-192837',
      notes: 'Oral mucosal administration.',
      completed: true,
      isPrediction: false,
    },
    {
      id: 'vac-4',
      petId: 'milo',
      name: 'Leptospirosis 4-Serovar Protection',
      category: 'Non-Core',
      status: 'Administered',
      alert: false,
      dueDate: 'Dec 05, 2026',
      administeredDate: 'Dec 05, 2025',
      vet: 'Bay Paws Clinic • Dr. Elena Rostova',
      tagNumber: 'LEP-002914',
      notes: 'Essential for mountain trail water exploration.',
      completed: true,
      isPrediction: false,
    },
    {
      id: 'pred-1',
      petId: 'milo',
      name: 'Canine Influenza (H3N8/H3N2)',
      category: 'Lifestyle',
      status: 'Predicted',
      alert: false,
      dueDate: 'Nov 15, 2026',
      notes: 'Recommended based on high social activity at local dog parks.',
      completed: false,
      isPrediction: true,
    },
    {
      id: 'pred-2',
      petId: 'milo',
      name: 'Lyme Disease Annual Booster',
      category: 'Non-Core',
      status: 'Predicted',
      alert: false,
      dueDate: 'Dec 10, 2026',
      notes: 'Standard annual booster for pets in coastal wooded areas.',
      completed: false,
      isPrediction: true,
    },
    {
      id: 'vac-luna-1',
      petId: 'luna',
      name: 'FVRCP Feline Core (Rhinotracheitis, Calicivirus, Panleukopenia)',
      category: 'Core',
      status: 'Due',
      alert: true,
      dueDate: 'Nov 12, 2026',
      administeredDate: 'Nov 10, 2025',
      vet: 'Feline Care Center • Dr. Mark Wu',
      tagNumber: 'FVRCP-440192',
      notes: 'Right front leg subcutaneous injection.',
      completed: false,
      isPrediction: false,
      manufacturer: 'Elanco Fel-O-Vax',
      batchNumber: 'FV-99201',
      verificationLevel: 'Clinic Verified',
    },
    {
      id: 'vac-luna-1-prev',
      petId: 'luna',
      name: 'FVRCP Feline Core',
      category: 'Core',
      status: 'Administered',
      alert: false,
      dueDate: 'Nov 10, 2025',
      administeredDate: 'Nov 08, 2024',
      vet: 'Feline Care Center • Dr. Mark Wu',
      tagNumber: 'FVRCP-1122',
      notes: 'Standard feline booster.',
      completed: true,
      isPrediction: false,
      manufacturer: 'Elanco Fel-O-Vax',
      verificationLevel: 'Clinic Verified',
    },
    {
      id: 'pred-3',
      petId: 'milo',
      name: 'Rattlesnake Vaccine (Crotalus Atrox)',
      category: 'Lifestyle',
      status: 'Predicted',
      alert: false,
      dueDate: 'Jan 20, 2027',
      notes: 'Recommended for active trail dogs in semi-arid climates.',
      completed: false,
      isPrediction: true,
    },
    {
      id: 'pred-luna-1',
      petId: 'luna',
      name: 'Feline Rabies Annual Booster',
      category: 'Core',
      status: 'Predicted',
      alert: false,
      dueDate: 'May 18, 2027',
      notes: 'Standard annual requirement for urban feline mobility.',
      completed: false,
      isPrediction: true,
    },
    {
      id: 'vac-luna-2',
      petId: 'luna',
      name: 'PureVax Feline Rabies 1-Year Non-Adjuvanted',
      category: 'Core',
      status: 'Administered',
      alert: false,
      dueDate: 'May 18, 2027',
      administeredDate: 'May 18, 2026',
      vet: 'Feline Care Center • Dr. Mark Wu',
      tagNumber: 'RAB-CAT-19028',
      notes: 'Right rear leg injection. Non-adjuvanted formulation.',
      completed: true,
      isPrediction: false,
    },
    {
      id: 'vac-luna-3',
      petId: 'luna',
      name: 'FeLV Feline Leukemia Virus Protection',
      category: 'Core',
      status: 'Administered',
      alert: false,
      dueDate: 'Jun 20, 2027',
      administeredDate: 'Jun 20, 2026',
      vet: 'Feline Care Center • Dr. Mark Wu',
      tagNumber: 'FELV-881023',
      notes: 'Left rear leg administration.',
      completed: true,
      isPrediction: false,
    },
    {
      id: 'pred-luna-1',
      petId: 'luna',
      name: 'FIP (Feline Infectious Peritonitis) Assessment',
      category: 'Lifestyle',
      status: 'Predicted',
      alert: false,
      dueDate: 'Mar 15, 2027',
      notes: 'Standard screening recommended for indoor/outdoor cat transitions.',
      completed: false,
      isPrediction: true,
    }
  ],
  medications: [
    {
      id: 'med-1',
      petId: 'milo',
      name: 'Simparica Trio Chewable (Flea, Tick, Heartworm)',
      dose: '1 chewable tablet (22-44 lbs)',
      schedule: '1st of every month with breakfast',
      frequency: 'Monthly',
      startDate: '2026-01-01',
      takenToday: true,
      lastTakenTime: '08:15 AM',
      notes: 'Administer with peanut butter or full food bowl.',
    },
    {
      id: 'med-2',
      petId: 'milo',
      name: 'Glucosamine & Chondroitin Joint Chews',
      dose: '2 soft chews daily',
      schedule: 'Daily morning meal',
      frequency: 'Daily',
      startDate: '2026-03-10',
      takenToday: true,
      lastTakenTime: '08:15 AM',
      notes: 'Maintains hip cartilage elasticity for active retrievers.',
    },
    {
      id: 'med-3',
      petId: 'milo',
      name: 'Wild Alaskan Salmon Oil Omega-3',
      dose: '2 pumps (5 ml)',
      schedule: 'Dinner topper',
      frequency: 'Daily',
      startDate: '2026-02-15',
      takenToday: false,
      notes: 'Coat radiance and EPA/DHA cardiovascular support.',
    },
    {
      id: 'med-luna-1',
      petId: 'luna',
      name: 'Revolution Plus Topical Solution (Cats 5.6-11 lbs)',
      dose: '1 single-dose tube (0.5 mL)',
      schedule: '1st of every month',
      frequency: 'Monthly',
      startDate: '2026-01-01',
      takenToday: true,
      lastTakenTime: '08:00 AM',
      notes: 'Part fur at base of head and press tube firmly.',
    },
    {
      id: 'med-luna-2',
      petId: 'luna',
      name: 'Feline Hairball Relief Maple Flavor Paste',
      dose: '1/2 teaspoon 2x weekly',
      schedule: 'Wednesday & Saturday evenings',
      frequency: 'Weekly',
      startDate: '2026-04-01',
      takenToday: false,
      notes: 'Administer directly from tube or smear on top of paw.',
    },
  ],
  routineTasks: [
    {
      id: 'task-1',
      petId: 'milo',
      time: '07:30 AM',
      title: 'Morning Pine Ridge Sniffari Walk',
      desc: '30 mins leisurely scent-tracking on mountain trail',
      completed: true,
      xp: 30,
      category: 'walk',
    },
    {
      id: 'task-2',
      petId: 'milo',
      time: '08:15 AM',
      title: 'Breakfast & Joint Chew Dispense',
      desc: '180g Pacific Salmon formula + 2 Glucosamine bites',
      completed: true,
      xp: 25,
      category: 'feed',
    },
    {
      id: 'task-3',
      petId: 'milo',
      time: '12:30 PM',
      title: 'Noon Hydration & Garden Frisbee Toss',
      desc: 'Refresh cold water fountain and 15 mins agility play',
      completed: true,
      xp: 20,
      category: 'play',
    },
    {
      id: 'task-4',
      petId: 'milo',
      time: '06:00 PM',
      title: 'Evening Salmon Supper & Omega Boost',
      desc: '180g portion with 2 pumps wild salmon oil',
      completed: false,
      xp: 25,
      category: 'feed',
    },
    {
      id: 'task-5',
      petId: 'milo',
      time: '08:45 PM',
      title: 'Nightly Oatmeal Paw Balm & Coat Detangle',
      desc: 'Inspect paw pads for burrs and soothe with organic balm',
      completed: false,
      xp: 15,
      category: 'groom',
    },
    {
      id: 'task-luna-1',
      petId: 'luna',
      time: '07:30 AM',
      title: 'Morning Feline Raw Feast (65g)',
      desc: 'Dispense organic rabbit pate with probiotic pumpkin topper',
      completed: true,
      xp: 25,
      category: 'feed',
    },
    {
      id: 'task-luna-2',
      petId: 'luna',
      time: '01:00 PM',
      title: 'Laser Pointer & Feather Wand Agility',
      desc: '15 mins interactive vertical leaps and hunting sprint play',
      completed: true,
      xp: 20,
      category: 'play',
    },
    {
      id: 'task-luna-3',
      petId: 'luna',
      time: '06:00 PM',
      title: 'Evening Salmon Pate & Water Fountain Check',
      desc: '65g portion with fresh filtered fountain refill',
      completed: false,
      xp: 25,
      category: 'feed',
    },
    {
      id: 'task-luna-4',
      petId: 'luna',
      time: '09:00 PM',
      title: 'Velvet Ruff Slicker Brush & Chin Scratches',
      desc: 'Prevent hairballs with 10 mins relaxing grooming strokes',
      completed: false,
      xp: 20,
      category: 'groom',
    },
  ],
  routines: [
    {
      id: 'rt-milo-daily',
      userId: 'default-user',
      petId: 'milo',
      name: "Milo's Daily Care Rhythm",
      description: 'Comprehensive daily routine with nutritious meals, scenic sniffaris, and evening paw balm.',
      icon: '🐕',
      accent: '#3b82f6',
      active: true,
      createdAt: Date.now() - 7 * 86400000,
      updatedAt: Date.now() - 86400000,
      items: [
        {
          id: 'item-milo-1',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Morning Trail Sniffari Walk',
          activityType: 'walk',
          category: 'activity',
          scheduledTime: '07:15 AM',
          durationMinutes: 30,
          repeatType: 'every_day',
          priority: 'high',
          location: 'Mountain Creek Trail',
          notes: 'Sniffing exploration at steady pace.',
          reminderEnabled: true,
          reminderOffset: 10,
          active: true,
          icon: '🐾',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
        {
          id: 'item-milo-2',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Breakfast & Joint Cartilage Chew',
          activityType: 'feeding',
          category: 'care',
          scheduledTime: '08:15 AM',
          durationMinutes: 10,
          repeatType: 'every_day',
          priority: 'high',
          quantity: 180,
          unit: 'g',
          notes: '180g Pacific Salmon formula + 2 Glucosamine chews',
          reminderEnabled: true,
          reminderOffset: 0,
          active: true,
          icon: '🍖',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
        {
          id: 'item-milo-3',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Noon Hydration & Frisbee Toss',
          activityType: 'play',
          category: 'activity',
          scheduledTime: '12:30 PM',
          durationMinutes: 20,
          repeatType: 'every_day',
          priority: 'medium',
          location: 'Backyard Green',
          notes: 'Fresh bowl of cold water + fetch sprints.',
          reminderEnabled: false,
          reminderOffset: 0,
          active: true,
          icon: '🎾',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
        {
          id: 'item-milo-4',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Evening Coastal Beach Sprint',
          activityType: 'walk',
          category: 'activity',
          scheduledTime: '05:45 PM',
          durationMinutes: 35,
          repeatType: 'every_day',
          priority: 'high',
          location: 'Crissy Field Shoreline',
          reminderEnabled: true,
          reminderOffset: 15,
          active: true,
          icon: '🏖️',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
        {
          id: 'item-milo-5',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Evening Salmon Supper & Omega Boost',
          activityType: 'feeding',
          category: 'care',
          scheduledTime: '06:45 PM',
          durationMinutes: 10,
          repeatType: 'every_day',
          priority: 'high',
          quantity: 180,
          unit: 'g',
          notes: '180g portion with 2 pumps wild salmon oil.',
          reminderEnabled: true,
          reminderOffset: 5,
          active: true,
          icon: '🍲',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
        {
          id: 'item-milo-6',
          routineId: 'rt-milo-daily',
          petId: 'milo',
          userId: 'default-user',
          title: 'Nightly Oatmeal Paw Balm & Detangle',
          activityType: 'grooming',
          category: 'care',
          scheduledTime: '08:45 PM',
          durationMinutes: 15,
          repeatType: 'every_day',
          priority: 'low',
          notes: 'Inspect pads for foxtails, apply soothing balm.',
          reminderEnabled: false,
          reminderOffset: 0,
          active: true,
          icon: '✨',
          createdAt: Date.now() - 7 * 86400000,
          updatedAt: Date.now() - 7 * 86400000,
        },
      ],
    },
    {
      id: 'rt-luna-daily',
      userId: 'default-user',
      petId: 'luna',
      name: "Luna's Feline Wellness Schedule",
      description: 'Raw feeding timetable, stimulating playtime, and coat grooming.',
      icon: '🐈',
      accent: '#8b5cf6',
      active: true,
      createdAt: Date.now() - 5 * 86400000,
      updatedAt: Date.now() - 86400000,
      items: [
        {
          id: 'item-luna-1',
          routineId: 'rt-luna-daily',
          petId: 'luna',
          userId: 'default-user',
          title: 'Morning Feline Raw Feast',
          activityType: 'feeding',
          category: 'care',
          scheduledTime: '07:30 AM',
          durationMinutes: 10,
          repeatType: 'every_day',
          priority: 'high',
          quantity: 65,
          unit: 'g',
          notes: 'Organic rabbit pate with probiotic pumpkin powder.',
          reminderEnabled: true,
          reminderOffset: 0,
          active: true,
          icon: '🐟',
          createdAt: Date.now() - 5 * 86400000,
          updatedAt: Date.now() - 5 * 86400000,
        },
        {
          id: 'item-luna-2',
          routineId: 'rt-luna-daily',
          petId: 'luna',
          userId: 'default-user',
          title: 'Laser Pointer & Feather Wand Agility',
          activityType: 'play',
          category: 'activity',
          scheduledTime: '01:00 PM',
          durationMinutes: 15,
          repeatType: 'every_day',
          priority: 'medium',
          notes: 'Vertical leaps and predatory sprint chase.',
          reminderEnabled: false,
          reminderOffset: 0,
          active: true,
          icon: '🪶',
          createdAt: Date.now() - 5 * 86400000,
          updatedAt: Date.now() - 5 * 86400000,
        },
        {
          id: 'item-luna-3',
          routineId: 'rt-luna-daily',
          petId: 'luna',
          userId: 'default-user',
          title: 'Evening Salmon Pate & Water Fountain Check',
          activityType: 'feeding',
          category: 'care',
          scheduledTime: '06:00 PM',
          durationMinutes: 10,
          repeatType: 'every_day',
          priority: 'high',
          quantity: 65,
          unit: 'g',
          notes: '65g portion with fresh filtered refill.',
          reminderEnabled: true,
          reminderOffset: 5,
          active: true,
          icon: '🍲',
          createdAt: Date.now() - 5 * 86400000,
          updatedAt: Date.now() - 5 * 86400000,
        },
        {
          id: 'item-luna-4',
          routineId: 'rt-luna-daily',
          petId: 'luna',
          userId: 'default-user',
          title: 'Velvet Ruff Slicker Brush & Chin Scratches',
          activityType: 'grooming',
          category: 'care',
          scheduledTime: '09:00 PM',
          durationMinutes: 15,
          repeatType: 'every_day',
          priority: 'medium',
          notes: '10 mins relaxing grooming strokes.',
          reminderEnabled: false,
          reminderOffset: 0,
          active: true,
          icon: '✨',
          createdAt: Date.now() - 5 * 86400000,
          updatedAt: Date.now() - 5 * 86400000,
        },
      ],
    },
  ],
  routineExecutions: [],
  healthMilestones: [
    {
      id: 'mil-1',
      petId: 'milo',
      title: 'Annual Physical & Blood Panel',
      date: 'Jun 12, 2026',
      desc: 'Comprehensive checkup: heart, lungs, eyes, ears, and teeth all optimal.',
      status: 'completed',
      badgeText: 'Cleared by Dr. Rostova',
    },
    {
      id: 'mil-2',
      petId: 'milo',
      title: 'DHPP 5-in-1 Booster Appointment',
      date: 'Oct 18, 2026',
      desc: 'Core immune antibody protection check at Bay Paws Specialty Clinic.',
      status: 'upcoming',
      badgeText: 'Appointment Confirmed',
    },
    {
      id: 'mil-3',
      petId: 'milo',
      title: 'Preventative Ultrasonic Dental Prophylaxis',
      date: 'Jan 15, 2027',
      desc: 'Tartar scaling and polishing under twilight sedation.',
      status: 'scheduled',
      badgeText: 'Routine Care',
    },
    {
      id: 'mil-luna-1',
      petId: 'luna',
      title: 'Annual Feline Comprehensive Physical & Bloodwork',
      date: 'May 18, 2026',
      desc: 'Full wellness screening with Dr. Mark Wu; organ functions pristine.',
      status: 'completed',
      badgeText: 'Cleared by Dr. Wu',
    },
    {
      id: 'mil-luna-2',
      petId: 'luna',
      title: 'FVRCP Feline 3-in-1 Booster Due',
      date: 'Nov 12, 2026',
      desc: 'Core feline protection booster at Feline Care Center.',
      status: 'upcoming',
      badgeText: 'Appointment Confirmed',
    },
  ],
  documents: [
    {
      id: 'doc-1',
      petId: 'milo',
      title: 'AKC Canine Good Citizen Certificate',
      type: 'PDF',
      subtitle: 'Issued by American Kennel Club • Dec 2025',
      size: '2.4 MB',
      code: 'AKC-CGC-88194',
      verified: true,
      date: 'Dec 15, 2025',
    },
    {
      id: 'doc-2',
      petId: 'milo',
      title: 'Official State Rabies Vaccine Certificate',
      type: 'PDF',
      subtitle: 'Certified by Bay Paws Clinic • Aug 2025',
      size: '1.8 MB',
      code: 'RAB-992018-CA',
      verified: true,
      date: 'Aug 14, 2025',
    },
    {
      id: 'doc-3',
      petId: 'milo',
      title: 'ISO Microchip Registration Certificate',
      type: 'PDF',
      subtitle: 'HomeAgain Registry #985141002938472',
      size: '1.1 MB',
      code: 'CHIP-985141',
      verified: true,
      date: 'Apr 02, 2024',
    },
  ],
};

export const TROPHIES_LIST = INITIAL_TROPHIES;
export const STORE_PRODUCTS = INITIAL_PRODUCTS;
